AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Esercizio04

  Sample SAM Template for Esercizio04

Globals:
  Function:
    Timeout: 3

Resources:
  RepeatFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        RepeatRule:
          Type: Schedule
          Properties:
            Schedule: 'cron(0/1 * * * ? *)'